services:
  DATA:
    image: postgres:15
    container_name: Smart_shop_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Smart_shop_db
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_Smart_shop
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@java.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - DATA

volumes:
  database:
